#define IDD_MISSION 46
#define IDD_LOGISTIC_MENU 75802

#define IDC_CLOSE_BUTTON 75801
#define IDC_LOGISTIC_LISTBOX 75802
#define IDC_CREATE_GROUP_BUTTON 75803
#define IDC_DELETE_GROUP_BUTTON 75804
#define IDC_LOGISTIC_NAME_TEXT 75805
#define IDC_LOGISTIC_STATUS_TEXT 75806
#define IDC_LOGISTIC_STATUS 75807
#define IDC_TIME_LABEL_TEXT 75808
#define IDC_TIME_LABEL 75809
#define IDC_DESTINATION_TEXT 758010
#define IDC_DESTINATION 758011
#define IDC_LOADED_TITLE 758012
#define IDC_TRUCK_COUNT_TEXT 758013
#define IDC_TRUCK_COUNT 758014
#define IDC_LOADED_SUPPLY_TEXT 758015
#define IDC_LOADED_SUPPLY 758016
#define IDC_LOADED_AMMO_TEXT 758017
#define IDC_LOADED_AMMO 758018
#define IDC_LOADED_FUEL_TEXT 758019
#define IDC_LOADED_FUEL 758020
#define IDC_BUY_TRUCK_BUTTON 758021
#define IDC_SELL_TRUCK_BUTTON 758022
#define IDC_A_TITLE 758023
#define IDC_A_COMBO 758024
#define IDC_A_SUPPLY_EDIT 758025
#define IDC_A_AMMO_EDIT 758026
#define IDC_A_FUEL_EDIT 758027
#define IDC_B_TITLE 758028
#define IDC_B_COMBO 758029
#define IDC_B_SUPPLY_EDIT 758030
#define IDC_B_AMMO_EDIT 758031
#define IDC_B_FUEL_EDIT 758032
#define IDC_A_LABEL_TEXT 758033
#define IDC_B_LABEL_TEXT 758034
#define IDC_SAVE_BUTTON 758035
#define IDC_ABORT_BUTTON 758036
#define IDC_MAP 758037
#define IDC_CLOSE2_BUTTON 758038

#define DETAIL_CONTROLS [\
    IDC_LOGISTIC_NAME_TEXT,\
    IDC_LOGISTIC_STATUS_TEXT,\
    IDC_LOGISTIC_STATUS,\
    IDC_TIME_LABEL_TEXT,\
    IDC_TIME_LABEL,\
    IDC_TIME_DESTINATION_TEXT,\
    IDC_TIME_DESTINATION,\
    IDC_LOADED_TITLE,\
    IDC_TRUCK_COUNT_TEXT,\
    IDC_TRUCK_COUNT,\
    IDC_LOADED_SUPPLY_TEXT,\
    IDC_LOADED_SUPPLY,\
    IDC_LOADED_AMMO_TEXT,\
    IDC_LOADED_AMMO,\
    IDC_LOADED_FUEL_TEXT,\
    IDC_LOADED_FUEL,\
    IDC_BUY_TRUCK_BUTTON,\
    IDC_SELL_TRUCK_BUTTON,\
    IDC_A_TITLE,\
    IDC_A_COMBO,\
    IDC_A_SUPPLY_EDIT,\
    IDC_A_AMMO_EDIT,\
    IDC_A_FUEL_EDIT,\
    IDC_B_TITLE,\
    IDC_B_COMBO,\
    IDC_B_SUPPLY_EDIT,\
    IDC_B_AMMO_EDIT,\
    IDC_B_FUEL_EDIT,\
    IDC_SAVE_BUTTON,\
    IDC_ABORT_BUTTON\
]

// Logi status
#define LOGI_NO_STATUS -1
#define LOGI_STATUS_STANDBY 0
#define LOGI_STATUS_AT_A_LOADING 1
#define LOGI_STATUS_AT_A_UNLOADING 2
#define LOGI_STATUS_TO_A 3
#define LOGI_STATUS_TO_B 4
#define LOGI_STATUS_AT_B_LOADING 5
#define LOGI_STATUS_AT_B_UNLOADING 6
#define LOGI_STATUS_ABORTING_TO_A 7
#define LOGI_STATUS_ABORTING_TO_B 8
#define LOGI_STATUS_AMBUSHED 9

// Special Flag
#define LOGI_NO_FLAG -1
#define LOGI_FLAG_NO_STORAGE 0
#define LOGI_FLAG_NO_RESOURCES 1

// Colors
#define COLOR_POSITIVE [0,0.9,0,1]
#define COLOR_NEUTRAL [1,1,1,1]
#define COLOR_NEGATIVE [0.9,0,0,1]
#define COLOR_LOADING [0.89,0.53,0.09,1]