// Logi status
#define LOGI_NO_STATUS -1
#define LOGI_STATUS_STANDBY 0
#define LOGI_STATUS_AT_A_LOADING 1
#define LOGI_STATUS_AT_A_UNLOADING 2
#define LOGI_STATUS_TO_A 3
#define LOGI_STATUS_TO_B 4
#define LOGI_STATUS_AT_B_LOADING 5
#define LOGI_STATUS_AT_B_UNLOADING 6
#define LOGI_STATUS_ABORTING_TO_A 7
#define LOGI_STATUS_ABORTING_TO_B 8
#define LOGI_STATUS_AMBUSHED 9

// Special Flag
#define LOGI_NO_FLAG -1
#define LOGI_FLAG_NO_STORAGE 0
#define LOGI_FLAG_NO_RESOURCES 1

// Logi data indexes
#define TRUCK_COUNT_INDEX 0
#define POINT_A_POS_INDEX 1
#define POINT_B_POS_INDEX 2
#define RES_TRANS_A_INDEX 3
#define RES_TRANS_B_INDEX 4
#define CURRENT_LOADED_INDEX 5
#define STATUS_INDEX 6
#define TIME_LEFT_INDEX 7
#define SPECIAL_FLAG_INDEX 8
#define LAST_POS_INDEX 9
#define PFH_ID_INDEX 10