name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-sqflint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install SQFLint
        run: pip install sqflint

      - name: Get changed SQF files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: Missionframework/**/*.sqf

      - name: Validate ONLY changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "--------------------------------------------------"
            echo "Linting: $file"
            # Removed --exit w so warnings don't fail the build
            sqflint "$file"
          done
